export const posts = {
  CREATE_POST: "CREATE_POST",
  READ_POSTS: "READ_POSTS",
  UPDATE_POST: "UPDATE_POST",
  UPDATE_LIKES: "UPDATE_LIKES",
  DELETE_POST: "DELETE_POST",
  DELETE_POSTS: "DELETE_POSTS"
}